export {
    resolveEditorConfig,
    resolveRawEditorConfig,
    resolveCSharpIndentationOptions,
    resolveCSharpNewLineOptions,
    resolveCSharpSpacingOptions,
    resolveCSharpWrappingOptions,
    resolveHtmlFormattingOptions,
    resolveIndentationOptions,
    resolveLineEnding,
    resolveMaxLineLength,
    resolveBoolean,
    resolveCharset,
} from "./editorConfigService";
export type {
    Charset,
    CSharpBinaryOperatorSpacing,
    CSharpIndentationOptions,
    CSharpLabelIndentation,
    CSharpNewLineOptions,
    CSharpOpenBraceContext,
    CSharpParenthesisSpacingContext,
    CSharpSpacingOptions,
    CSharpWrappingOptions,
    EditorConfigFallback,
    HtmlAttributeIndent,
    HtmlAttributeStyle,
    HtmlAttributeWrapPolicy,
    HtmlExtraSpaces,
    HtmlFormattingOptions,
    IndentationOptions,
    IndentationStyle,
    LineEnding,
    ResolvedEditorConfigProperties,
    WorkbenchEditorConfig,
} from "./models";
