<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>CSharpWorkbench.Roslyn.Core</AssemblyName>
    <RootNamespace>CSharpWorkbench.Roslyn.Core</RootNamespace>
    <VersionPrefix>0.2.0</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>
</Project>
